### ISSUE TITLE
Have depth based control for visuals (e.g. layering)

### ISSUE THREAD

**Issue by RustoMCSpit** [Houston4444/HoustonPatchbay#10]
The user should be able to choose manually (and set up automatically) what wire / i/o is in "front" of the other like how in Powerpoint if you had two images you'd have to pick which takes the priority layer as seen here https://youtu.be/XA8FF89OfJU?t=15

The user should be able to have it automatically put certain things forward such as their favourite app etc..

**Comment by Houston4444** [comment]
Honestly, I think almost (maybe all) users use the "prevent overlap" feature, so, there are no layers in the patchbay.
