### ISSUE TITLE
Allow people / apps to change the buffer size, sample rate, etc.

### ISSUE THREAD

**Issue by RustoMCSpit** [Houston4444/HoustonPatchbay#18]
you can change these settings in /usr/share/pipewire/pipewire.conf or your distros equilavent i think
also if possible having different settings for each connection / device would be cool

**Comment by Houston4444** [comment]
Change buffer size is already possible.
Change buffersize independently for device is probably possible on pipewire (I don't know), for connections I really doubt.

**Comment by RustoMCSpit** [comment]
> Change buffer size is already possible. Change buffersize independently for device is probably possible on pipewire (I don't know), for connections I really doubt.

could you make a feature request for it then in jack?
