### ISSUE TITLE
Ability to play / pause audio from RayS

### ISSUE THREAD

**Issue by RustoMCSpit** [Houston4444/HoustonPatchbay#19]
Select one or multiple nodes and play or pause them, could be used to doubletrack to AI cloned Youtube videos in sync for example and then panned to each ear for a surreal but amazing sound.

**Comment by Houston4444** [comment]
"play or pause them" takes no sense for almost boxes (nodes). Anyway, there is no command for a such thing in the JACK API (used by RaySession and Patchance).

**Comment by RustoMCSpit** [comment]
> "play or pause them" takes no sense for almost boxes (nodes). Anyway, there is no command for a such thing in the JACK API (used by RaySession and Patchance).

could you make a feature request for it then in jack?
